services:
  openclaw-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENCLAW_DOCKER_APT_PACKAGES: ffmpeg
    image: docker-registry.home-intra.net/openclaw/gateway:latest
    ports: !reset []
    networks:
      - home-server
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw:z
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace:z
    security_opt:
      - label=disable

  openclaw-cli:
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw:z
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace:z

networks:
  home-server:
    external: true
    name: home-server_home-server
